"""add uploaded_at default

Revision ID: 510e38b335ee
Revises: 3b17e62f380d
Create Date: 2026-09-09 20:17:10.687471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510e38b335ee'
down_revision: Union[str, Sequence[str], None] = '3b17e62f380d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uploaded_files_stored_name_key'), 'uploaded_files', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uploaded_files_stored_name_key'), 'uploaded_files', ['stored_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
