"""make response_id nullable

Revision ID: 62538de0c854
Revises: 97a52a670ff3
Create Date: 2026-09-04 10:33:04.675352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62538de0c854'
down_revision: Union[str, Sequence[str], None] = '97a52a670ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'response_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'response_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
